import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CreateGameButton from "../components/HomePageButtons/CreateGameButton";
import JoinGameButton from "../components/HomePageButtons/JoinGameButton";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home_menu}>
        <CreateGameButton />
        <JoinGameButton />
      </div>
    </div>
  );
}
